name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # <-- แก้ไขบรรทัดนี้ให้ถูกต้อง

      - name: Create firebase-config.js
        run: |
          echo "export const firebaseConfig = {" >> js/firebase-config.js
          echo "  apiKey: \"${{ secrets.FIREBASE_API_KEY }}\"," >> js/firebase-config.js
          echo "  authDomain: \"${{ secrets.FIREBASE_AUTH_DOMAIN }}\"," >> js/firebase-config.js
          echo "  projectId: \"${{ secrets.FIREBASE_PROJECT_ID }}\"," >> js/firebase-config.js
          echo "  storageBucket: \"${{ secrets.FIREBASE_STORAGE_BUCKET }}\"," >> js/firebase-config.js
          echo "  messagingSenderId: \"${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}\"," >> js/firebase-config.js
          echo "  appId: \"${{ secrets.FIREBASE_APP_ID }}\"," >> js/firebase-config.js
          echo "  measurementId: \"${{ secrets.FIREBASE_MEASUREMENT_ID }}\"" >> js/firebase-config.js
          echo "};" >> js/firebase-config.js

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
